version: '3.9'

services:
  kong:
    image: 'kong/kong-gateway:3.5.0.1'
    container_name: kong
    hostname: kong
    environment:
      KONG_PG_HOST: 'kong-database'
      KONG_PG_USER: 'kong'
      KONG_PG_DATABASE: 'kong'
      KONG_PG_PASSWORD: 'kong'
      KONG_PROXY_ACCESS_LOG: '/dev/stdout'
      KONG_ADMIN_ACCESS_LOG: '/dev/stdout'
      KONG_PROXY_ERROR_LOG: '/dev/stderr'
      KONG_ADMIN_ERROR_LOG: '/dev/stderr'
      KONG_ADMIN_LISTEN: '0.0.0.0:8001, 0.0.0.0:8444 ssl'
    # command: kong migrations up
    networks:
      - kong-net
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    depends_on:
      - postgress

  postgress:
    image: 'postgres:15.5'
    container_name: 'kong-database'
    hostname: 'kong-database'
    environment:
      POSTGRES_USER: 'kong'
      POSTGRES_DB: 'kong'
      POSTGRES_PASSWORD: 'kong'
    ports:
      - "5432:5432"
    networks:
      - kong-net
  konga:
    image: 'pantsel/konga'
    container_name: konga
    hostname: konga
    networks:
      - kong-net
    ports:
      - "1337:1337"
    environment:
      NODE_ENV: 'production'
      TOKEN_SECRET: '345w3erfesrw34r5qwerfwerw'
networks:
  kong-net:
